version: '3'
services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './App:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
