# Build app
FROM node:13-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY App/package.json /app/package.json
RUN npm i --silent
RUN npm i react-script --silent
COPY App /app
RUN npm run build

# Deploy
FROM nginx:1.21-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
